// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXveLre2NWPvXgklzkn7OQ34OxbyXVQNM',
    appId: '1:934302133797:web:30ed404257b37d65b359cc',
    messagingSenderId: '934302133797',
    projectId: 'java-c9a00',
    authDomain: 'java-c9a00.firebaseapp.com',
    databaseURL: 'https://java-c9a00.firebaseio.com',
    storageBucket: 'java-c9a00.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiAGzKojLrLDULm0ZA3rHD_0BwWVyDNwQ',
    appId: '1:934302133797:android:3055f7f739e8466bb359cc',
    messagingSenderId: '934302133797',
    projectId: 'java-c9a00',
    databaseURL: 'https://java-c9a00.firebaseio.com',
    storageBucket: 'java-c9a00.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7KgVmJOMKwIYzlU6MSy7UjyddrjvCeXk',
    appId: '1:934302133797:ios:f97e02d156674d49b359cc',
    messagingSenderId: '934302133797',
    projectId: 'java-c9a00',
    databaseURL: 'https://java-c9a00.firebaseio.com',
    storageBucket: 'java-c9a00.firebasestorage.app',
    androidClientId: '934302133797-gko4sqrm54s2fn06qjqrb1bo9rj1le6n.apps.googleusercontent.com',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7KgVmJOMKwIYzlU6MSy7UjyddrjvCeXk',
    appId: '1:934302133797:ios:f97e02d156674d49b359cc',
    messagingSenderId: '934302133797',
    projectId: 'java-c9a00',
    databaseURL: 'https://java-c9a00.firebaseio.com',
    storageBucket: 'java-c9a00.firebasestorage.app',
    androidClientId: '934302133797-gko4sqrm54s2fn06qjqrb1bo9rj1le6n.apps.googleusercontent.com',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXveLre2NWPvXgklzkn7OQ34OxbyXVQNM',
    appId: '1:934302133797:web:c52c6c94217fe515b359cc',
    messagingSenderId: '934302133797',
    projectId: 'java-c9a00',
    authDomain: 'java-c9a00.firebaseapp.com',
    databaseURL: 'https://java-c9a00.firebaseio.com',
    storageBucket: 'java-c9a00.firebasestorage.app',
  );
}
