// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNhp-HzMJGl5ZG6GOq6e2BtC395Sviokg',
    appId: '1:1047876844049:web:6eb1fd5e52a4c53df50fb0',
    messagingSenderId: '1047876844049',
    projectId: 'dvsd-db0d5',
    authDomain: 'dvsd-db0d5.firebaseapp.com',
    storageBucket: 'dvsd-db0d5.firebasestorage.app',
    measurementId: 'G-HE9RRYCVHB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB76qPbkBgXI35eK3zDx0Rc3uVCRbKaYiU',
    appId: '1:1047876844049:android:3c4646bbc466e88df50fb0',
    messagingSenderId: '1047876844049',
    projectId: 'dvsd-db0d5',
    storageBucket: 'dvsd-db0d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7uelBft2Kz7PuxJ02pkASMUNZZSYTBvo',
    appId: '1:1047876844049:ios:1390e50e9c4f526df50fb0',
    messagingSenderId: '1047876844049',
    projectId: 'dvsd-db0d5',
    storageBucket: 'dvsd-db0d5.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7uelBft2Kz7PuxJ02pkASMUNZZSYTBvo',
    appId: '1:1047876844049:ios:1390e50e9c4f526df50fb0',
    messagingSenderId: '1047876844049',
    projectId: 'dvsd-db0d5',
    storageBucket: 'dvsd-db0d5.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNhp-HzMJGl5ZG6GOq6e2BtC395Sviokg',
    appId: '1:1047876844049:web:f9a45d981dac5261f50fb0',
    messagingSenderId: '1047876844049',
    projectId: 'dvsd-db0d5',
    authDomain: 'dvsd-db0d5.firebaseapp.com',
    storageBucket: 'dvsd-db0d5.firebasestorage.app',
    measurementId: 'G-QFVJ258VPQ',
  );
}